import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Apex Combat Aesthetic palette
        background: "#1d100d",
        surface: "#1d100d",
        "surface-tint": "#ffb4a8",
        "surface-dim": "#1d100d",
        "surface-bright": "#473532",
        "surface-container-lowest": "#180b08",
        "surface-container-low": "#271815",
        "surface-container": "#2b1c19",
        "surface-container-high": "#362623",
        "surface-container-highest": "#42312e",
        "surface-variant": "#42312e",
        "on-surface": "#f8dcd7",
        "on-surface-variant": "#e3beb8",
        "inverse-surface": "#f8dcd7",
        "inverse-on-surface": "#3d2c29",
        outline: "#aa8984",
        "outline-variant": "#5a403c",
        primary: "#ffb4a8",
        "on-primary": "#690000",
        "primary-container": "#d83f2e",
        "on-primary-container": "#140000",
        "inverse-primary": "#b52518",
        "primary-fixed": "#ffdad4",
        "primary-fixed-dim": "#ffb4a8",
        "on-primary-fixed": "#410000",
        "on-primary-fixed-variant": "#920502",
        secondary: "#ffb4a8",
        "on-secondary": "#5e170e",
        "secondary-container": "#7f2f24",
        "on-secondary-container": "#ff9f90",
        "secondary-fixed": "#ffdad4",
        "secondary-fixed-dim": "#ffb4a8",
        "on-secondary-fixed": "#400201",
        "on-secondary-fixed-variant": "#7c2d22",
        tertiary: "#ebc078",
        "on-tertiary": "#422c00",
        "tertiary-container": "#b18a48",
        "on-tertiary-container": "#3a2600",
        "tertiary-fixed": "#ffdeab",
        "tertiary-fixed-dim": "#ebc078",
        "on-tertiary-fixed": "#281900",
        "on-tertiary-fixed-variant": "#5f4103",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "on-background": "#f8dcd7",
      },
      fontFamily: {
        display: ['var(--font-anybody)', "Anybody", "system-ui", "sans-serif"],
        headline: ['var(--font-anybody)', "Anybody", "system-ui", "sans-serif"],
        body: ['var(--font-inter)', "Inter", "system-ui", "sans-serif"],
        mono: ['ui-monospace', "SFMono-Regular", "Menlo", "monospace"],
        "headline-md": ['var(--font-anybody)', "Anybody", "sans-serif"],
        "headline-xl": ['var(--font-anybody)', "Anybody", "sans-serif"],
        "display-lg": ['var(--font-anybody)', "Anybody", "sans-serif"],
        "headline-md-mobile": ['var(--font-anybody)', "Anybody", "sans-serif"],
        "body-lg": ['var(--font-inter)', "Inter", "sans-serif"],
        "body-md": ['var(--font-inter)', "Inter", "sans-serif"],
        "label-bold": ['var(--font-inter)', "Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["72px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-xl": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md-mobile": ["24px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      spacing: {
        unit: "8px",
        "container-max": "1280px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "section-gap": "80px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      backgroundImage: {
        "primary-gradient":
          "linear-gradient(135deg, rgba(216, 63, 46, 0.15) 0%, rgba(185, 91, 77, 0.05) 100%)",
        "edge-glow":
          "linear-gradient(135deg, rgba(255, 180, 168, 0.18) 0%, rgba(255, 180, 168, 0) 100%)",
      },
    },
  },
  plugins: [],
};

export default config;
